name: Docker WorkFlow
on: push

jobs:
  build:
    name: Hello Docker-WorkFlow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Alice"
      - name: steps/name
      - run: echo "Hello from jobs/build/steps/name"
